// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4DWMfWq8Dm4x7L_YzTHGDBk5QYb1F_g',
    appId: '1:764594631643:web:901533129bb9f3a7bcadfe',
    messagingSenderId: '764594631643',
    projectId: 'fairouzuser-f6436',
    authDomain: 'fairouzuser-f6436.firebaseapp.com',
    storageBucket: 'fairouzuser-f6436.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ7JRaaRGr5mkzyGtwibh61JlE3HyBDGk',
    appId: '1:764594631643:android:ade2d28c61185c55bcadfe',
    messagingSenderId: '764594631643',
    projectId: 'fairouzuser-f6436',
    storageBucket: 'fairouzuser-f6436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2wajyqloVRvHCveGfe_SbSkTPCbBncAU',
    appId: '1:764594631643:ios:26371554004560e8bcadfe',
    messagingSenderId: '764594631643',
    projectId: 'fairouzuser-f6436',
    storageBucket: 'fairouzuser-f6436.firebasestorage.app',
    iosBundleId: 'com.fairouz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2wajyqloVRvHCveGfe_SbSkTPCbBncAU',
    appId: '1:764594631643:ios:310e199ba3fc3d40bcadfe',
    messagingSenderId: '764594631643',
    projectId: 'fairouzuser-f6436',
    storageBucket: 'fairouzuser-f6436.firebasestorage.app',
    iosBundleId: 'com.example.fairouz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH4DWMfWq8Dm4x7L_YzTHGDBk5QYb1F_g',
    appId: '1:764594631643:web:9923a2c7bbe476c0bcadfe',
    messagingSenderId: '764594631643',
    projectId: 'fairouzuser-f6436',
    authDomain: 'fairouzuser-f6436.firebaseapp.com',
    storageBucket: 'fairouzuser-f6436.firebasestorage.app',
  );
}
